---
- include_tasks: ufw_wireguard_server.yaml
- include_tasks: install_wg.yaml


- name: copy docker-compose
  template:
    dest: "/home/{{ sys.user }}/docker-compose.yaml"
    src: docker-compose.j2
    owner: "{{ sys.user }}"
    group: "{{ sys.user }}"
    mode: '0776'


#- name: start wgui
#  shell:
#    cmd: docker compose up -d
#    chdir: "/home/{{ sys.user }}/"
